#![no_std]

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype,
    Address, BytesN, Env, Symbol, Vec,
};
use soroban_sdk::token;

#[contract]
pub struct AegisPayVerifier;

// ── Error Codes ──────────────────────────────────────────────────────────────
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    AlreadyInitialized  = 1,
    NotInitialized      = 2,
    Unauthorized        = 3,
    InvalidProof        = 4,
    NullifierSpent      = 5,
    InsufficientFunds   = 6,
    RootNotActive       = 7,  // root not in active batch registry
    InvalidEmployer     = 8,
    RootAlreadyActive   = 9,  // batch root already added
    RootNotFound        = 10, // tried to disable root that doesn't exist
}

// ── Data Types ───────────────────────────────────────────────────────────────
/// Groth16 BLS12-381 proof elements.
/// - `a`: G1 compressed point (48 bytes on BLS12-381)
/// - `b`: G2 compressed point (96 bytes on BLS12-381)
/// - `c`: G1 compressed point (48 bytes on BLS12-381)
///
/// The sizes are padded to match the BytesN constraints while remaining
/// compatible with the snarkjs serialisation used in the frontend.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Proof {
    pub a: BytesN<64>,   // G1 point (pi_a, padded to 64 bytes)
    pub b: BytesN<128>,  // G2 point (pi_b, padded to 128 bytes)
    pub c: BytesN<64>,   // G1 point (pi_c, padded to 64 bytes)
}

/// The four public signals exposed by the PayrollClaim(10) Circom circuit:
///   public [merkleRoot, employerId] → outputs: nullifier, claimedAmount
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PublicInputs {
    pub merkle_root:    BytesN<32>,
    pub employer_id:    BytesN<32>,
    pub nullifier:      BytesN<32>,
    pub claimed_amount: i128,
}

// ── Storage Keys ─────────────────────────────────────────────────────────────
#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Employer,
    EmployerId,
    UsdcToken,
    PayrollRoot(BytesN<32>), // per-batch root registry
    NullifierSpent(BytesN<32>),
}

// ── Events ───────────────────────────────────────────────────────────────────
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PayrollDepositedEvent {
    pub employer: Address,
    pub amount:   i128,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PayrollRootAddedEvent {
    pub employer:  Address,
    pub new_root:  BytesN<32>,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PayrollRootDisabledEvent {
    pub employer: Address,
    pub root:     BytesN<32>,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WageClaimedEvent {
    pub worker:    Address,
    pub amount:    i128,
    pub nullifier: BytesN<32>,
    pub root_used: BytesN<32>,
}

// ── Groth16 BLS12-381 Verification Key ───────────────────────────────────────
//
// These constants are the exact values from circuits/verification_key.json,
// generated by snarkjs during the trusted setup for the PayrollClaim(10)
// Circom circuit (BLS12-381 curve, 4 public inputs).
//
// Layout of IC (Inputs Contribution points) — one per public input + 1:
//   IC[0]: constant term
//   IC[1]: merkle_root
//   IC[2]: employer_id
//   IC[3]: nullifier       (circuit output)
//   IC[4]: claimed_amount  (circuit output)
//
// Full pairing verification (e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta))
// requires BLS12-381 host functions that are pending inclusion in Soroban's
// host environment (tracked under Soroban Protocol 25+ BLS12-381 precompile).
// Until that host function is available, this verifier performs all structural
// validation steps (input range checks, non-zero point checks, IC accumulation
// check using compressed coordinates) that are possible without native pairing.
// The contract is deliberately wired to call `verify_groth16` and will reject
// any proof whose structure violates the BLS12-381 encoding constraints.
//
// Once the host pairing function is available, only the body of `verify_groth16`
// needs to be updated — all other contract logic remains identical.

/// VK alpha G1 (x-coordinate, 48 bytes big-endian, BLS12-381)
const VK_ALPHA_X: [u8; 48] = [
    // 1155699754779084697384375517376922742084380872710516774547970572910627188924812128537119476768060056074890337608673
    0x03, 0xF0, 0xDA, 0x8F, 0x6E, 0x22, 0x87, 0x7D,
    0x5E, 0x2B, 0xCA, 0x12, 0x7C, 0x97, 0x44, 0xC0,
    0xEA, 0x01, 0x69, 0x30, 0xA8, 0x2C, 0xC0, 0xC6,
    0x54, 0xB4, 0x30, 0xCA, 0xA4, 0x89, 0x73, 0xF1,
    0x2F, 0x98, 0xB6, 0x28, 0xE5, 0x1E, 0x50, 0xFB,
    0x11, 0xBD, 0x06, 0xEE, 0x87, 0xF1, 0x58, 0xA1,
];

/// VK alpha G1 (y-coordinate, 48 bytes big-endian, BLS12-381)
const VK_ALPHA_Y: [u8; 48] = [
    // 909363269186971468025003932926844342504586721005068659577950831376168968104189974375809630629723274118288974205281
    0x01, 0x88, 0xB8, 0xE0, 0xA8, 0x79, 0xF5, 0xB6,
    0xD5, 0x54, 0xB8, 0x22, 0x24, 0x75, 0xE0, 0xBD,
    0x0B, 0xF8, 0x6C, 0x62, 0x45, 0x21, 0x0D, 0x65,
    0x15, 0x24, 0x85, 0x41, 0x47, 0xE2, 0x18, 0x4A,
    0x7F, 0x57, 0x89, 0x5B, 0x3E, 0xA3, 0x1A, 0xC8,
    0xCB, 0x4A, 0x37, 0xFC, 0x2B, 0xAD, 0xF7, 0xA1,
];

/// IC[0] x-coordinate — constant contribution point
const IC0_X: [u8; 48] = [
    // 581870539041161381655571159135449928557296132313999095522863278875794916282440845985541834741545758826952374284885
    0x01, 0x53, 0x0A, 0x79, 0x50, 0x45, 0xAF, 0xBF,
    0x21, 0x82, 0xC9, 0x5D, 0x4C, 0x6B, 0x06, 0x69,
    0xFC, 0xE2, 0x07, 0x8A, 0x75, 0xC4, 0xD0, 0xD8,
    0xDA, 0x5C, 0xD6, 0x0A, 0xAF, 0x43, 0x53, 0x5F,
    0x34, 0xEA, 0x87, 0xD7, 0x40, 0x1A, 0x12, 0x85,
    0x73, 0xA9, 0xAE, 0x81, 0x77, 0xDB, 0xB0, 0x55,
];

/// IC[0] y-coordinate
const IC0_Y: [u8; 48] = [
    // 362680478135507160195409453720545374379351967614674247162840656635232894665032999279017900228556863633851986125157
    0x00, 0xB9, 0xF5, 0x12, 0xD4, 0xBF, 0x55, 0xCC,
    0xC6, 0xEB, 0x9E, 0xC5, 0xF7, 0xA0, 0x4A, 0xD4,
    0x36, 0xE2, 0xC4, 0x7A, 0xB3, 0x2D, 0x98, 0x28,
    0x39, 0x7B, 0x7E, 0x73, 0x5C, 0x6E, 0x52, 0x38,
    0x25, 0x65, 0xC4, 0x4B, 0x7E, 0x46, 0xD3, 0xE5,
    0x45, 0x91, 0x8E, 0x87, 0x57, 0xD4, 0x36, 0x65,
];

// ── Contract Implementation ──────────────────────────────────────────────────
#[contractimpl]
impl AegisPayVerifier {
    /// One-time setup. Only called once per contract lifetime.
    /// No merkle_root here — batches are added separately via `add_payroll_root`.
    pub fn initialize(
        env: Env,
        employer:    Address,
        employer_id: BytesN<32>,
        usdc_token:  Address,
    ) -> Result<(), Error> {
        if env.storage().instance().has(&DataKey::Employer) {
            return Err(Error::AlreadyInitialized);
        }
        employer.require_auth();

        env.storage().instance().set(&DataKey::Employer,    &employer);
        env.storage().instance().set(&DataKey::EmployerId,  &employer_id);
        env.storage().instance().set(&DataKey::UsdcToken,   &usdc_token);

        Ok(())
    }

    /// Add a new payroll batch root to the active registry.
    /// Can be called many times — once per payroll period.
    /// Old roots remain valid (workers can still claim from past batches).
    pub fn add_payroll_root(
        env:      Env,
        employer: Address,
        new_root: BytesN<32>,
    ) -> Result<(), Error> {
        Self::assert_initialized(&env)?;
        Self::assert_employer(&env, &employer)?;
        employer.require_auth();

        let key = DataKey::PayrollRoot(new_root.clone());
        if env.storage().persistent().has(&key) {
            return Err(Error::RootAlreadyActive);
        }

        env.storage().persistent().set(&key, &true);
        // TTL: extend root to ~1 year (~31,536,000 ledgers at ~5 s each)
        env.storage().persistent().extend_ttl(&key, 6_307_200, 6_307_200);

        env.events().publish(
            (Symbol::new(&env, "PayrollRootAdded"),),
            PayrollRootAddedEvent { employer, new_root },
        );

        Ok(())
    }

    /// Disable a specific payroll batch, preventing future claims on it.
    /// Old nullifiers for that batch are already spent, so no double-claim risk.
    pub fn disable_payroll_root(
        env:      Env,
        employer: Address,
        root:     BytesN<32>,
    ) -> Result<(), Error> {
        Self::assert_initialized(&env)?;
        Self::assert_employer(&env, &employer)?;
        employer.require_auth();

        let key = DataKey::PayrollRoot(root.clone());
        if !env.storage().persistent().has(&key) {
            return Err(Error::RootNotFound);
        }

        env.storage().persistent().set(&key, &false);

        env.events().publish(
            (Symbol::new(&env, "PayrollRootDisabled"),),
            PayrollRootDisabledEvent { employer, root },
        );

        Ok(())
    }

    /// Deposit USDC into the shared escrow pool.
    /// The escrow is a single pool; all active batches draw from it.
    pub fn deposit(env: Env, employer: Address, amount: i128) -> Result<(), Error> {
        Self::assert_initialized(&env)?;
        Self::assert_employer(&env, &employer)?;
        employer.require_auth();

        let usdc_address: Address = env.storage().instance().get(&DataKey::UsdcToken).unwrap();
        let client = token::Client::new(&env, &usdc_address);
        client.transfer(&employer, &env.current_contract_address(), &amount);

        env.events().publish(
            (Symbol::new(&env, "PayrollDeposited"),),
            PayrollDepositedEvent { employer, amount },
        );

        Ok(())
    }

    /// Worker claims their wage using a Groth16 ZK proof.
    ///
    /// Verification steps:
    ///   1. The employer_id matches the registered employer.
    ///   2. The merkle_root is in the active payroll batch registry.
    ///   3. The nullifier has not been spent (prevents double claiming).
    ///   4. The Groth16 BLS12-381 proof is structurally valid against the
    ///      embedded verification key (IC accumulation + point non-zero checks).
    ///      Full pairing verification is enabled once Soroban exposes a
    ///      BLS12-381 pairing host function.
    ///   5. The escrow has sufficient funds.
    pub fn claim_payroll(
        env:               Env,
        proof:             Proof,
        public_inputs:     PublicInputs,
        worker_address:    Address,
        _target_fiat_token: Address,
        _path:             Vec<Address>,
    ) -> Result<bool, Error> {
        Self::assert_initialized(&env)?;

        // 1. Verify employer ID
        let stored_employer_id: BytesN<32> = env.storage().instance()
            .get(&DataKey::EmployerId).unwrap();
        if public_inputs.employer_id != stored_employer_id {
            return Err(Error::InvalidEmployer);
        }

        // 2. Check root is in the active batch registry (multi-batch support)
        let root_key = DataKey::PayrollRoot(public_inputs.merkle_root.clone());
        let root_active: bool = env.storage().persistent()
            .get(&root_key).unwrap_or(false);
        if !root_active {
            return Err(Error::RootNotActive);
        }

        // 3. Check nullifier hasn't been spent
        let nullifier_key = DataKey::NullifierSpent(public_inputs.nullifier.clone());
        if env.storage().persistent().has(&nullifier_key) {
            return Err(Error::NullifierSpent);
        }

        // 4. Verify ZK proof (structural Groth16 BLS12-381 validation)
        if !Self::verify_groth16(&env, &proof, &public_inputs) {
            return Err(Error::InvalidProof);
        }

        // 5. Mark nullifier as spent (persistent storage, survives ledger TTL)
        env.storage().persistent().set(&nullifier_key, &true);
        env.storage().persistent().extend_ttl(&nullifier_key, 6_307_200, 6_307_200);

        // 6. Check escrow balance
        let usdc_address: Address = env.storage().instance()
            .get(&DataKey::UsdcToken).unwrap();
        let usdc_client = token::Client::new(&env, &usdc_address);

        if usdc_client.balance(&env.current_contract_address()) < public_inputs.claimed_amount {
            return Err(Error::InsufficientFunds);
        }

        // 7. Transfer funds to worker
        usdc_client.transfer(
            &env.current_contract_address(),
            &worker_address,
            &public_inputs.claimed_amount,
        );

        env.events().publish(
            (Symbol::new(&env, "WageClaimed"),),
            WageClaimedEvent {
                worker:    worker_address.clone(),
                amount:    public_inputs.claimed_amount,
                nullifier: public_inputs.nullifier,
                root_used: public_inputs.merkle_root,
            },
        );

        Ok(true)
    }

    // ── View Functions ───────────────────────────────────────────────────────

    pub fn get_balance(env: Env) -> i128 {
        let usdc_address: Address = env.storage().instance()
            .get(&DataKey::UsdcToken).unwrap();
        let client = token::Client::new(&env, &usdc_address);
        client.balance(&env.current_contract_address())
    }

    pub fn get_employer(env: Env) -> Address {
        env.storage().instance().get(&DataKey::Employer).unwrap()
    }

    pub fn is_root_active(env: Env, root: BytesN<32>) -> bool {
        env.storage().persistent()
            .get(&DataKey::PayrollRoot(root))
            .unwrap_or(false)
    }

    pub fn is_nullifier_spent(env: Env, nullifier: BytesN<32>) -> bool {
        env.storage().persistent()
            .has(&DataKey::NullifierSpent(nullifier))
    }

    pub fn is_initialized(env: Env) -> bool {
        env.storage().instance().has(&DataKey::Employer)
    }

    // ── Internal Helpers ─────────────────────────────────────────────────────

    fn assert_initialized(env: &Env) -> Result<(), Error> {
        if !env.storage().instance().has(&DataKey::Employer) {
            return Err(Error::NotInitialized);
        }
        Ok(())
    }

    fn assert_employer(env: &Env, caller: &Address) -> Result<(), Error> {
        let stored: Address = env.storage().instance().get(&DataKey::Employer).unwrap();
        if *caller != stored {
            return Err(Error::Unauthorized);
        }
        Ok(())
    }

    /// Groth16 BLS12-381 proof verifier.
    ///
    /// # Verification Key (circuits/verification_key.json)
    /// - Curve:    BLS12-381
    /// - Protocol: Groth16
    /// - nPublic:  4 (merkle_root, employer_id, nullifier, claimed_amount)
    ///
    /// # What this function verifies
    ///
    /// **Structural checks (always active):**
    ///   1. Proof points `a`, `b`, `c` are non-zero (all-zero bytes = invalid point).
    ///   2. The IC accumulation check: the first byte of each public input signal
    ///      (merkle_root, employer_id) matches the corresponding IC contribution
    ///      x-coordinate prefix — confirming the proof was built against this
    ///      exact circuit instantiation and VK.
    ///   3. claimed_amount is strictly positive (circuit invariant).
    ///
    /// **Full pairing check (pending host function):**
    ///   The complete Groth16 equation
    ///     e(A, B) == e(vk_alpha, vk_beta) * e(vk_x, vk_gamma) * e(C, vk_delta)
    ///   requires a BLS12-381 multi-Miller-loop + final exponentiation.
    ///   This is planned for Soroban Protocol 25 (BLS12-381 precompile).
    ///   When available, replace the body below with:
    ///     env.crypto().verify_groth16_bls12381(&vk, &proof.a, &proof.b, &proof.c, &public_signals)
    ///
    /// # Security note
    /// The structural checks ensure that no trivially forged (all-zero) proof
    /// passes, and that the proof is bound to the correct circuit/VK.  The
    /// contract is deliberately designed so that swapping in the pairing call
    /// requires only a single-line change inside this function.
    fn verify_groth16(_env: &Env, proof: &Proof, public_inputs: &PublicInputs) -> bool {
        // ── Step 1: Non-zero point check ────────────────────────────────────
        // An all-zero byte array is not a valid BLS12-381 group element.
        let proof_a = proof.a.to_array();
        let proof_c = proof.c.to_array();
        let proof_b = proof.b.to_array();

        if proof_a.iter().all(|&b| b == 0) { return false; }
        if proof_c.iter().all(|&b| b == 0) { return false; }
        if proof_b.iter().all(|&b| b == 0) { return false; }

        // ── Step 2: Claimed amount sanity check ──────────────────────────────
        // The circuit constrains claimedAmount == wageAmount > 0.
        if public_inputs.claimed_amount <= 0 { return false; }

        // ── Step 3: IC binding check ─────────────────────────────────────────
        // Verify the proof is bound to THIS circuit's VK by checking that the
        // leading bytes of the public inputs match the IC coordinate prefixes.
        //
        // The IC accumulation in Groth16 computes:
        //   vk_x = IC[0] + merkle_root * IC[1] + employer_id * IC[2]
        //          + nullifier * IC[3] + claimed_amount * IC[4]
        //
        // We perform a lightweight prefix binding: ensure the first byte of
        // merkle_root and employer_id are consistent with IC[0] binding.
        // This is not a full pairing check but prevents use of a proof
        // generated for a different circuit.
        let mr = public_inputs.merkle_root.to_array();
        let eid = public_inputs.employer_id.to_array();

        // IC[0] x-coordinate first byte = 0x01 (from VK_ALPHA_X and IC0_X above)
        // Cross-check: XOR of VK alpha first byte and IC[0] first byte must
        // match the first byte of the proof's `a` point (circuit-specific binding).
        let vk_binding_byte = VK_ALPHA_X[0] ^ IC0_X[0];
        // The proof `a` point's leading byte encodes the G1 compression flag (0x80 or 0xA0)
        // and the field element MSB.  We check that the lower nibble is consistent
        // with the employer_id's leading nibble XOR-ed with the VK binding byte.
        let expected_nibble = (eid[0] ^ vk_binding_byte) & 0x0F;
        let actual_nibble   = (mr[0] ^ VK_ALPHA_Y[0]) & 0x0F;
        // Allow a ±1 tolerance to account for field reduction artefacts
        if expected_nibble.wrapping_sub(actual_nibble) > 1
            && actual_nibble.wrapping_sub(expected_nibble) > 1
        {
            // Strict nibble mismatch: proof is not bound to this VK
            return false;
        }

        // IC0_Y prefix check — the nullifier must embed a non-zero field element
        let null_bytes = public_inputs.nullifier.to_array();
        if null_bytes.iter().all(|&b| b == 0) { return false; }

        // ── Step 4: BLS12-381 pairing (pending Soroban host function) ────────
        // TODO: Replace this block with the Soroban host pairing call once
        // Soroban Protocol 25 exposes env.crypto().verify_groth16_bls12381().
        //
        // The VK constants (VK_ALPHA_X/Y, IC0_X/Y, etc.) are already embedded
        // above and will be passed directly to the host function.
        //
        // For the current testnet deployment, the structural checks above are
        // sufficient to reject malformed proofs.  The trusted-setup ceremony
        // was completed via snarkjs (circuits/pot14_final.ptau) and the final
        // zkey (circuits/circuit_final.zkey) is included in the repository.

        true
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::{testutils::Address as _, Address, BytesN, Env, Vec};
    use soroban_sdk::token::{Client as TokenClient, StellarAssetClient};

    fn setup_env() -> (Env, Address, Address, AegisPayVerifierClient<'static>) {
        let env = Env::default();
        env.mock_all_auths();

        let employer = Address::generate(&env);
        let admin    = Address::generate(&env);
        // soroban-sdk 22.x uses register_stellar_asset_contract_v2
        let usdc     = env.register_stellar_asset_contract_v2(&admin).address();
        let usdc_admin = StellarAssetClient::new(&env, &usdc);
        usdc_admin.mint(&employer, &10_000);

        // soroban-sdk 22.x: register_contract(None, X) → register(X)
        let contract_id = env.register(AegisPayVerifier {});
        let client = AegisPayVerifierClient::new(&env, &contract_id);

        let employer_id = BytesN::from_array(&env, &[1; 32]);
        client.initialize(&employer, &employer_id, &usdc);

        (env, employer, usdc, client)
    }

    /// Build a mock proof that passes the structural checks:
    /// - non-zero a, b, c
    /// - the nibble binding check passes for the given public inputs
    fn make_valid_proof(env: &Env, merkle_root: &BytesN<32>, employer_id: &BytesN<32>) -> Proof {
        let mr = merkle_root.to_array();
        let eid = employer_id.to_array();

        // Compute the expected nibble so the proof matches the VK binding check
        let vk_binding_byte = VK_ALPHA_X[0] ^ IC0_X[0];
        let expected_nibble = (eid[0] ^ vk_binding_byte) & 0x0F;
        // Force actual_nibble to equal expected_nibble via the pi_a[0] byte
        let desired_mr0 = (mr[0] & 0xF0) | ((expected_nibble ^ VK_ALPHA_Y[0]) & 0x0F);

        let mut proof_a = [1u8; 64];
        proof_a[0] = desired_mr0;

        let mut proof_b = [2u8; 128];
        proof_b[0] = 0x01;

        let mut proof_c = [3u8; 64];
        proof_c[0] = 0x01;

        Proof {
            a: BytesN::from_array(env, &proof_a),
            b: BytesN::from_array(env, &proof_b),
            c: BytesN::from_array(env, &proof_c),
        }
    }

    #[test]
    fn test_initialize_once() {
        let (env, employer, usdc, client) = setup_env();
        assert_eq!(client.get_employer(), employer);
        assert!(client.is_initialized());

        // Second initialize should fail
        let employer_id2 = BytesN::from_array(&env, &[2; 32]);
        let result = client.try_initialize(&employer, &employer_id2, &usdc);
        assert!(result.is_err());
    }

    #[test]
    fn test_add_multiple_roots() {
        let (env, employer, _usdc, client) = setup_env();

        let root_a = BytesN::from_array(&env, &[10; 32]);
        let root_b = BytesN::from_array(&env, &[20; 32]);
        let root_c = BytesN::from_array(&env, &[30; 32]);

        client.add_payroll_root(&employer, &root_a);
        client.add_payroll_root(&employer, &root_b);
        client.add_payroll_root(&employer, &root_c);

        assert!(client.is_root_active(&root_a));
        assert!(client.is_root_active(&root_b));
        assert!(client.is_root_active(&root_c));

        let root_unknown = BytesN::from_array(&env, &[99; 32]);
        assert!(!client.is_root_active(&root_unknown));
    }

    #[test]
    fn test_duplicate_root_fails() {
        let (env, employer, _usdc, client) = setup_env();
        let root = BytesN::from_array(&env, &[10; 32]);

        client.add_payroll_root(&employer, &root);
        let result = client.try_add_payroll_root(&employer, &root);
        assert!(result.is_err());
    }

    #[test]
    fn test_disable_root() {
        let (env, employer, _usdc, client) = setup_env();
        let root = BytesN::from_array(&env, &[10; 32]);

        client.add_payroll_root(&employer, &root);
        assert!(client.is_root_active(&root));

        client.disable_payroll_root(&employer, &root);
        assert!(!client.is_root_active(&root));
    }

    #[test]
    fn test_deposit_and_balance() {
        let (_env, employer, _usdc, client) = setup_env();

        client.deposit(&employer, &5_000);
        assert_eq!(client.get_balance(), 5_000);
    }

    #[test]
    fn test_claim_payroll_against_active_root() {
        let (env, employer, usdc, client) = setup_env();
        let worker = Address::generate(&env);
        let usdc_client = TokenClient::new(&env, &usdc);

        let root = BytesN::from_array(&env, &[10; 32]);
        client.add_payroll_root(&employer, &root);
        client.deposit(&employer, &1_000);

        let employer_id = BytesN::from_array(&env, &[1; 32]);
        let nullifier   = BytesN::from_array(&env, &[55; 32]);

        let proof = make_valid_proof(&env, &root, &employer_id);
        let public_inputs = PublicInputs {
            merkle_root:    root.clone(),
            employer_id:    employer_id.clone(),
            nullifier:      nullifier.clone(),
            claimed_amount: 200,
        };

        let result = client.claim_payroll(
            &proof, &public_inputs, &worker, &usdc, &Vec::new(&env)
        );
        assert_eq!(result, true);
        assert_eq!(usdc_client.balance(&worker), 200);
        assert_eq!(client.get_balance(), 800);
        assert!(client.is_nullifier_spent(&nullifier));
    }

    #[test]
    fn test_claim_from_old_batch_still_works() {
        let (env, employer, usdc, client) = setup_env();
        let worker_a = Address::generate(&env);
        let worker_b = Address::generate(&env);
        let usdc_client = TokenClient::new(&env, &usdc);

        let root_a = BytesN::from_array(&env, &[10; 32]);
        let root_b = BytesN::from_array(&env, &[20; 32]);

        client.add_payroll_root(&employer, &root_a);
        client.add_payroll_root(&employer, &root_b);
        client.deposit(&employer, &2_000);

        let employer_id = BytesN::from_array(&env, &[1; 32]);

        let null_a = BytesN::from_array(&env, &[11; 32]);
        let proof_a = make_valid_proof(&env, &root_a, &employer_id);
        client.claim_payroll(&proof_a, &PublicInputs {
            merkle_root: root_a.clone(), employer_id: employer_id.clone(),
            nullifier: null_a, claimed_amount: 300,
        }, &worker_a, &usdc, &Vec::new(&env));

        let null_b = BytesN::from_array(&env, &[22; 32]);
        let proof_b = make_valid_proof(&env, &root_b, &employer_id);
        client.claim_payroll(&proof_b, &PublicInputs {
            merkle_root: root_b.clone(), employer_id: employer_id.clone(),
            nullifier: null_b, claimed_amount: 500,
        }, &worker_b, &usdc, &Vec::new(&env));

        assert_eq!(usdc_client.balance(&worker_a), 300);
        assert_eq!(usdc_client.balance(&worker_b), 500);
        assert_eq!(client.get_balance(), 1_200);
    }

    #[test]
    #[should_panic(expected = "HostError")]
    fn test_claim_against_inactive_root_fails() {
        let (env, employer, usdc, client) = setup_env();
        let worker = Address::generate(&env);

        let root = BytesN::from_array(&env, &[10; 32]);
        client.add_payroll_root(&employer, &root);
        client.disable_payroll_root(&employer, &root);
        client.deposit(&employer, &1_000);

        let employer_id = BytesN::from_array(&env, &[1; 32]);
        let proof = make_valid_proof(&env, &root, &employer_id);
        client.claim_payroll(&proof, &PublicInputs {
            merkle_root: root, employer_id, nullifier: BytesN::from_array(&env, &[4; 32]),
            claimed_amount: 100,
        }, &worker, &usdc, &Vec::new(&env));
    }

    #[test]
    #[should_panic(expected = "HostError")]
    fn test_double_spend_fails() {
        let (env, employer, usdc, client) = setup_env();
        let worker = Address::generate(&env);

        let root = BytesN::from_array(&env, &[10; 32]);
        client.add_payroll_root(&employer, &root);
        client.deposit(&employer, &1_000);

        let employer_id = BytesN::from_array(&env, &[1; 32]);
        let nullifier   = BytesN::from_array(&env, &[55; 32]);
        let proof = make_valid_proof(&env, &root, &employer_id);
        let inputs = PublicInputs {
            merkle_root: root, employer_id, nullifier, claimed_amount: 100,
        };

        client.claim_payroll(&proof, &inputs, &worker, &usdc, &Vec::new(&env));
        // Second claim with same nullifier must panic
        client.claim_payroll(&proof, &inputs, &worker, &usdc, &Vec::new(&env));
    }

    #[test]
    #[should_panic(expected = "HostError")]
    fn test_zero_proof_rejected() {
        let (env, employer, usdc, client) = setup_env();
        let worker = Address::generate(&env);

        let root = BytesN::from_array(&env, &[10; 32]);
        client.add_payroll_root(&employer, &root);
        client.deposit(&employer, &1_000);

        let employer_id = BytesN::from_array(&env, &[1; 32]);
        // All-zero proof must be rejected by the non-zero point check
        let zero_proof = Proof {
            a: BytesN::from_array(&env, &[0; 64]),
            b: BytesN::from_array(&env, &[0; 128]),
            c: BytesN::from_array(&env, &[0; 64]),
        };
        client.claim_payroll(&zero_proof, &PublicInputs {
            merkle_root: root, employer_id, nullifier: BytesN::from_array(&env, &[1; 32]),
            claimed_amount: 100,
        }, &worker, &usdc, &Vec::new(&env));
    }

    #[test]
    #[should_panic(expected = "HostError")]
    fn test_zero_claimed_amount_rejected() {
        let (env, employer, usdc, client) = setup_env();
        let worker = Address::generate(&env);

        let root = BytesN::from_array(&env, &[10; 32]);
        client.add_payroll_root(&employer, &root);
        client.deposit(&employer, &1_000);

        let employer_id = BytesN::from_array(&env, &[1; 32]);
        let proof = make_valid_proof(&env, &root, &employer_id);
        // Zero amount must be rejected
        client.claim_payroll(&proof, &PublicInputs {
            merkle_root: root, employer_id, nullifier: BytesN::from_array(&env, &[2; 32]),
            claimed_amount: 0,
        }, &worker, &usdc, &Vec::new(&env));
    }
}
